name = 'aistock-extapi'
main = "src/index.ts"
compatibility_date = "2026-06-08"
compatibility_flags = ["nodejs_compat"]

# 为了打包文档等非代码文件，开启以下选项
find_additional_modules = true
base_dir = "."
preserve_file_names = true

[[rules]]
type = "Text"
globs = ["README.md"]
fallthrough = true

[vars]
# 微信公众号 AppID
WECHAT_APPID = "wx61330ef0702949b8"
# 前端首页地址（登录成功后跳转）
FRONTEND_URL = "https://my-stock-dashboard-251.pages.dev"
COOKIE_DOMAIN = "102465.xyz"
CORS_ALLOW_ORIGIN = "*"

# 大模型评价接口地址
OPENAI_API_BASE_URL = "https://gen.pollinations.ai/v1/chat/completions"
EVA_MODEL = "openai"
OCR_MODEL = "openai"

# 敏感信息请通过 wrangler secret put 设置:
#   wrangler secret put WECHAT_SECRET
#   wrangler secret put JWT_SECRET
#   wrangler secret put OPENAI_API_KEY

# KV Namespace binding
[[kv_namespaces]]
binding = "KV"
id = "b5bf6ad60737483fb9110e8d02201141"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "aistock-db"
database_id = "2178be35-6244-4c5a-8cdb-483af180a5b0" # 运行 wrangler d1 create aistock 后填入

# [[routes]]
# pattern = "stock-api.102465.xyz"
# custom_domain = true

[[routes]]
pattern = "microice.dpdns.org"
custom_domain = true

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[placement]
mode = "smart"
